name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    # - name: Setup Nim
    #   uses: jiro4989/setup-nim-action@v2
    #   with:
    #     nim-version: 'stable'
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Update bindings
    #   run: nim docs update_bindings.nims
    # - name: Commit updated docs
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git add .
    #     git commit -m "Update bindings for release ${{ github.ref_name }}"
    #     git push
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Naylib ${{ github.ref_name }} released! 🎉
